'use client';

import { useState, useEffect } from 'react';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import { FileText, Download, Filter, BarChart3 } from 'lucide-react';

interface Report {
  id: string;
  title: string;
  date: string;
  type: string;
  threats: number;
  blocked: number;
  status: 'completed' | 'pending' | 'failed';
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [filterType, setFilterType] = useState('all');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        // Fetch data from API
        const logsResponse = await fetch('http://127.0.0.1:8000/api/logs');
        const threatsResponse = await fetch('http://127.0.0.1:8000/api/threats');
        
        const logs = await logsResponse.json();
        const threats = await threatsResponse.json();

        // Generate mock reports based on data
        const mockReports: Report[] = [
          {
            id: '1',
            title: 'Daily Security Summary - Today',
            date: new Date().toISOString().split('T')[0],
            type: 'daily',
            threats: threats.length,
            blocked: logs.filter((l: any) => l.status_code === 403).length,
            status: 'completed'
          },
          {
            id: '2',
            title: 'Weekly Threat Analysis Report',
            date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
            type: 'weekly',
            threats: Math.floor(threats.length * 1.5),
            blocked: Math.floor(logs.filter((l: any) => l.status_code === 403).length * 1.2),
            status: 'completed'
          },
          {
            id: '3',
            title: 'Monthly Compliance Report',
            date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
            type: 'monthly',
            threats: Math.floor(threats.length * 3),
            blocked: Math.floor(logs.filter((l: any) => l.status_code === 403).length * 2.5),
            status: 'completed'
          }
        ];

        setReports(mockReports);
      } catch (error) {
        console.error('Failed to fetch reports:', error);
        setReports([]);
      } finally {
        setIsLoading(false);
      }
    };

    fetchReports();
  }, []);

  const filteredReports = reports.filter(r =>
    filterType === 'all' ? true : r.type === filterType
  );

  const downloadReport = (reportId: string) => {
    const report = reports.find(r => r.id === reportId);
    if (!report) return;

    const content = `
SECURITY REPORT
================

Title: ${report.title}
Date: ${report.date}
Type: ${report.type.toUpperCase()}
Status: ${report.status}

SUMMARY
-------
Total Threats Detected: ${report.threats}
Requests Blocked: ${report.blocked}
Threats Mitigated: ${report.threats - report.blocked}

RECOMMENDATIONS
---------------
1. Review and patch identified vulnerabilities
2. Implement additional rate limiting on critical endpoints
3. Monitor unusual access patterns from identified IPs
4. Conduct security training for developers

This report was generated by API Cortex Security Platform
    `.trim();

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
    element.setAttribute('download', `report_${reportId}_${report.date}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <div className="flex flex-1">
        <Sidebar />
        <main className="flex-1 p-6 overflow-y-auto bg-gradient-to-br from-slate-950 to-slate-900">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold mb-2">Security Reports</h1>
            <p className="text-gray-400">Generate, view, and download security analysis reports</p>
          </div>

          {/* Filter and Actions */}
          <div className="flex items-center gap-4 mb-8">
            <div className="flex items-center">
              <Filter size={20} className="text-gray-400 mr-2" />
              <select
                value={filterType}
                onChange={(e) => setFilterType(e.target.value)}
                className="bg-card border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-cyan-500/50"
              >
                <option value="all">All Reports</option>
                <option value="daily">Daily Reports</option>
                <option value="weekly">Weekly Reports</option>
                <option value="monthly">Monthly Reports</option>
              </select>
            </div>
          </div>

          {/* Reports Grid */}
          {isLoading ? (
            <div className="text-center text-gray-400 py-12">Loading reports...</div>
          ) : filteredReports.length === 0 ? (
            <div className="bg-card border border-white/10 rounded-lg p-12 text-center">
              <FileText className="mx-auto mb-4 text-gray-600" size={48} />
              <p className="text-gray-400">No reports found</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredReports.map(report => (
                <div key={report.id} className="bg-card border border-white/10 rounded-lg overflow-hidden hover:border-cyan-500/30 transition">
                  <div className="p-6 border-b border-white/10">
                    <div className="flex items-start justify-between mb-2">
                      <h3 className="font-bold text-lg flex-1">{report.title}</h3>
                      <span
                        className={`text-xs font-bold px-2 py-1 rounded ${
                          report.status === 'completed'
                            ? 'bg-green-500/20 text-green-400'
                            : report.status === 'pending'
                            ? 'bg-yellow-500/20 text-yellow-400'
                            : 'bg-red-500/20 text-red-400'
                        }`}
                      >
                        {report.status}
                      </span>
                    </div>
                    <p className="text-sm text-gray-400">{report.date}</p>
                  </div>

                  <div className="p-6 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="text-gray-400 text-sm">Threats Detected</span>
                      <span className="font-bold text-red-400">{report.threats}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-gray-400 text-sm">Requests Blocked</span>
                      <span className="font-bold text-green-400">{report.blocked}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-gray-400 text-sm">Type</span>
                      <span className="text-xs bg-slate-800 text-gray-300 px-2 py-1 rounded capitalize">
                        {report.type}
                      </span>
                    </div>
                  </div>

                  <div className="p-6 border-t border-white/10">
                    <button
                      onClick={() => downloadReport(report.id)}
                      className="w-full bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded transition flex items-center justify-center"
                    >
                      <Download size={18} className="mr-2" />
                      Download Report
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Statistics Section */}
          {!isLoading && reports.length > 0 && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
              <div className="bg-card border border-white/10 rounded-lg p-6">
                <div className="flex items-center mb-4">
                  <BarChart3 className="text-cyan-500 mr-2" size={24} />
                  <h3 className="text-lg font-bold">Total Reports</h3>
                </div>
                <p className="text-4xl font-bold text-cyan-400">{filteredReports.length}</p>
              </div>

              <div className="bg-card border border-white/10 rounded-lg p-6">
                <div className="flex items-center mb-4">
                  <BarChart3 className="text-red-500 mr-2" size={24} />
                  <h3 className="text-lg font-bold">Total Threats</h3>
                </div>
                <p className="text-4xl font-bold text-red-400">
                  {filteredReports.reduce((sum, r) => sum + r.threats, 0)}
                </p>
              </div>

              <div className="bg-card border border-white/10 rounded-lg p-6">
                <div className="flex items-center mb-4">
                  <BarChart3 className="text-green-500 mr-2" size={24} />
                  <h3 className="text-lg font-bold">Total Blocked</h3>
                </div>
                <p className="text-4xl font-bold text-green-400">
                  {filteredReports.reduce((sum, r) => sum + r.blocked, 0)}
                </p>
              </div>
            </div>
          )}
        </main>
      </div>
    </div>
  );
}
