'use client';

import { useState, useEffect } from 'react';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import { FileText, Download, Filter, AlertTriangle } from 'lucide-react';

interface Report {
  id: string;
  timestamp: string;
  attack_type: string;
  target_api: string;
  source_ip: string;
  detection_model: string;
  action_taken: string;
  recommended_prevention: string;
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [filterType, setFilterType] = useState('all');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const reportsResponse = await fetch('http://localhost:8000/api/reports');
        const data = await reportsResponse.json();
        setReports(Array.isArray(data) ? data : []);
      } catch (error) {
        console.error('Failed to fetch reports:', error);
        setReports([]);
      } finally {
        setIsLoading(false);
      }
    };

    fetchReports();
    // Refresh every 5 seconds
    const interval = setInterval(fetchReports, 5000);
    return () => clearInterval(interval);
  }, []);

  const filteredReports = reports.filter(r =>
    filterType === 'all' ? true : r.attack_type === filterType
  );

  const downloadReport = (report: Report) => {
    const content = `
SECURITY INCIDENT REPORT
========================

Attack Type: ${report.attack_type}
Target API: ${report.target_api}
Source IP: ${report.source_ip}
Timestamp: ${report.timestamp}
Detection Model: ${report.detection_model}
Action Taken: ${report.action_taken}

RECOMMENDED PREVENTION METHODS
------------------------------
${report.recommended_prevention.split(' | ').map((rec) => `• ${rec}`).join('\n')}

This report was auto-generated by API Cortex Autonomous Response System
    `.trim();

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
    element.setAttribute('download', `security_report_${report.id}_${new Date(report.timestamp).toISOString().split('T')[0]}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <div className="flex flex-1">
        <Sidebar />
        <main className="flex-1 p-6 overflow-y-auto bg-gradient-to-br from-slate-950 to-slate-900">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold mb-2">Security Incident Reports</h1>
            <p className="text-gray-400">Automated security reports generated by the detection and response system</p>
          </div>

          {/* Filter */}
          <div className="flex items-center gap-4 mb-8">
            <Filter size={20} className="text-gray-400" />
            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
              className="bg-card border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-cyan-500/50"
            >
              <option value="all">All Incident Types</option>
              <option value="SQL Injection">SQL Injection</option>
              <option value="DDoS/Flooding">DDoS/Flooding</option>
              <option value="Brute Force">Brute Force</option>
              <option value="Shadow API Access">Shadow API Access</option>
              <option value="Geolocation Anomaly">Geolocation Anomaly</option>
            </select>
          </div>

          {/* Reports */}
          {isLoading ? (
            <div className="text-center text-gray-400 py-12">Loading incident reports...</div>
          ) : filteredReports.length === 0 ? (
            <div className="bg-card border border-white/10 rounded-lg p-12 text-center">
              <FileText className="mx-auto mb-4 text-gray-600" size={48} />
              <p className="text-gray-400">No incident reports yet. Trigger an attack simulation to generate reports.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {filteredReports.map((report) => (
                <div key={report.id} className="bg-card border border-white/10 rounded-lg overflow-hidden hover:border-cyan-500/30 transition">
                  <div className="p-6 border-b border-white/10">
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <AlertTriangle className="text-alert-red" size={20} />
                        <h3 className="font-bold text-lg">{report.attack_type}</h3>
                      </div>
                    </div>
                    <p className="text-sm text-gray-400">{new Date(report.timestamp).toLocaleString()}</p>
                  </div>

                  <div className="p-6 space-y-3">
                    <div>
                      <span className="text-xs text-gray-500 uppercase font-bold">Target API</span>
                      <p className="text-sm font-mono text-gray-300">{report.target_api}</p>
                    </div>
                    <div>
                      <span className="text-xs text-gray-500 uppercase font-bold">Source IP</span>
                      <p className="text-sm font-mono text-gray-300">{report.source_ip}</p>
                    </div>
                    <div>
                      <span className="text-xs text-gray-500 uppercase font-bold">Action Taken</span>
                      <p className="text-sm text-cyan-400">{report.action_taken}</p>
                    </div>
                    <div>
                      <span className="text-xs text-gray-500 uppercase font-bold">Detection Model</span>
                      <p className="text-sm text-gray-300">{report.detection_model}</p>
                    </div>
                  </div>

                  <div className="p-6 border-t border-white/10">
                    <button
                      onClick={() => downloadReport(report)}
                      className="w-full bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded transition flex items-center justify-center gap-2"
                    >
                      <Download size={18} />
                      Download Report
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Summary Stats */}
          {!isLoading && reports.length > 0 && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
              <div className="bg-card border border-white/10 rounded-lg p-6">
                <h3 className="text-sm font-bold text-gray-500 uppercase mb-2">Total Incidents</h3>
                <p className="text-4xl font-bold text-cyan-400">{reports.length}</p>
              </div>
              <div className="bg-card border border-white/10 rounded-lg p-6">
                <h3 className="text-sm font-bold text-gray-500 uppercase mb-2">Most Common Attack</h3>
                <p className="text-lg font-bold text-gray-300">
                  {reports.length > 0
                    ? Object.entries(
                        reports.reduce(
                          (acc, r) => ({ ...acc, [r.attack_type]: (acc[r.attack_type as keyof typeof acc] || 0) + 1 }),
                          {} as Record<string, number>
                        )
                      ).sort(([, a], [, b]) => b - a)[0]?.[0] || 'N/A'
                    : 'N/A'}
                </p>
              </div>
              <div className="bg-card border border-white/10 rounded-lg p-6">
                <h3 className="text-sm font-bold text-gray-500 uppercase mb-2">Response Rate</h3>
                <p className="text-4xl font-bold text-green-400">100%</p>
              </div>
            </div>
          )}
        </main>
      </div>
    </div>
  );
}
